name: wallet_core
author: Lior Rabin <lior9586@gmail.com>
version: 0.2.5+1
homepage: https://github.com/fuseio/wallet_core
description: Fuse wallet core Dart library to interact with Ethereum based networks and APIs.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  bip32: ^1.0.10
  bip39: ^1.0.6
  hex: ^0.2.0
  http: ^0.13.1
  resource: ^2.1.7
  web3dart: ^2.0.0-dev.9
  graphql: ^4.0.1
  decimal: ^1.0.0+1
