name: wallet_core
author: Lior Rabin <lior9586@gmail.com>
version: 0.2.5+1
homepage: https://github.com/fuseio/wallet_core
description: Fuse wallet core Dart library to interact with Ethereum based networks and APIs.
publish_to: 'none'
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
# dart.dev
  http: ^0.13.3

# other
  bip32: ^1.0.10
  bip39: ^1.0.6
  decimal: ^1.1.0
  graphql: ^4.0.1
  hex: ^0.2.0
  web3dart: ^2.0.0